services:
  app:
    restart: on-failure
    depends_on:
      mysqlserver:
        condition: service_healthy
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlserver:$MYSQL_DOCKER_PORT/$MYSQL_DB
      SPRING_DATASOURCE_USERNAME: $MYSQL_USER
      SPRING_DATASOURCE_PASSWORD: $MYSQL_PASSWORD
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:$DEBUG_PORT
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT

  mysqlserver:
    image: mysql
    restart: on-failure
    env_file: ./.env
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB
    healthcheck:
      test: [$COMMAND_PROMPT, $MYSQL_PING_CHECK]
      timeout: 30s
      start_period: 5s
      interval: 5s
      retries: 3
